//Data Types in JavaScript
//Javascript is a Dynamic programming (var a=45) is automatic number type in javascript

// 1.Numbers:
//Integers: Integer (negative, zero and positive) numbers Example: ... -3, -2, -1, 0, 1, 2, 3 ...
//Float-point numbers: Decimal number Example ... -3.5, -2.25, -1.0, 0.0, 1.1, 2.2, 3.5 ...

let length = 16;
let weight = 7.5;
console.log(length, weight, typeof length); //16 7.5 "number"

// 2.Strings:
//A collection of one or more characters between two single quotes, double quotes, or backticks.

let color = "Yellow";
let lastName = "Johnson";
console.log(color, lastName, typeof color); //Yellow Johnson string
//let surName='Asabeneh';
//let nickName=`mahi`;

// 3.Booleans:
//A boolean value is either True or False. Any comparisons returns a boolean value, which is either true or false.
//A boolean data type is either a true or false value.

let x = true;
let y = false;
console.log(x, y, typeof x); //true false boolean

// 4.Undefined:
//In JavaScript, if we don't assign a value to a variable, the value is undefined. In addition to that, if a function is not returning anything, it returns undefined.

let firstName;
console.log(firstName, typeof firstName); // undefined, because it is not assigned to a value yet

// 5.Null
// Null in JavaScript means an empty value.

let emptyValue = null;
console.log(emptyValue, typeof emptyValue); //null,object

//6.Symbol
let id = Symbol();
console.log(id, typeof id); //Symbol

// 1.Object:
const person = { firstName: "John", lastName: "Doe" };
console.log(person, typeof person); //{firstName: 'John', lastName: 'Doe'} 'object'

// 2.Array object:
const cars = ["Saab", "Volvo", "BMW"];
console.log(cars, typeof cars); //["Saab", "Volvo", "BMW"] 'object'

// 3.Date object:
const date = new Date("2022-03-25");
console.log(date, typeof date); //today date 'object'

/*
JavaScript primitive data types:

1.String   ex:"selvamanan"
2.Number   ex:  1.25,25
3.Boolean  ex:  True,False
4.Null   ex: empty value or no value
5.Undefined  ex:a declared variable without a value
6.Symbols  E6 A unique value that can be generated by Symbol constructor
7.bigint  es2020

JavaScript non-primitive data types or complex data type (Object References)

1.Array
2.Object Literals
3.Date

*/

//1.primitive Data Type is not modify and mutable:
let word = "JavaScript";
word[0] = "m";
console.log(word); //Javascript

let numOne = 3;
let numTwo = 3;
console.log(numOne == numTwo); // true

let js = "JavaScript";
let py = "Python";
console.log(js == py); //false

let lightOn = true;
let lightOff = false;
console.log(lightOn == lightOff); // false

//2.Non-Primitive data type
//Non-primitive data types are modifiable or mutable

let nums = [1, 2, 3];
nums[0] = 10;
console.log(nums); // [10, 2, 3]

//As you can see, an array, which is a non-primitive data type is mutable. Non-primitive data types cannot be compared by value. Even if two non-primitive data types have the same properties and values, they are not strictly equal.

let nums1 = [1, 2, 3];
let numbers = [1, 2, 3];
console.log(nums1 == numbers); // false

let userOne = {
  name: "Asabeneh",
  role: "teaching",
  country: "Finland",
};

let userTwo = {
  name: "Asabeneh",
  role: "teaching",
  country: "Finland",
};
console.log(userOne == userTwo); // false

//Rule of thumb, we do not compare non-primitive data types. Do not compare arrays, functions, or objects. Non-primitive values are referred to as reference types, because they are being compared by reference instead of value. Two objects are only strictly equal if they refer to the same underlying object.

let nums2 = [1, 2, 3];
let numbers1 = nums2;

console.log(nums2 == numbers1); // true

let userOne1 = {
  name: "Asabeneh",
  role: "teaching",
  country: "Finland",
};

let userTwo1 = userOne1;

console.log(userOne1 == userTwo1); // true

//1.Numbers:

/*
Most programming languages have many number types:

Whole numbers (integers):
byte (8-bit), short (16-bit), int (32-bit), long (64-bit)

Real numbers (floating-point):
float (32-bit), double (64-bit).

Javascript numbers are always one type:
double (64-bit floating point).
*/

// With decimals:
let x1 = 34.0;
console.log("with decimals", x1); //34

// Without decimals:
let x2 = 34;
console.log("without decimals", x2); //34

var age = 23; //Number Literal
var gpay = 34.6;
console.log(age); //23
console.log(typeof age); //Number
console.log(gpay); //34.6

//var octNumber = 0255;
var hexNum = 0xff;
//console.log(octNumber);//previous octNumber is a zero not printing
console.log(hexNum); //255

var amt = 1.1e6;
console.log(amt); //1100000

let price = 200.0; // interpreted as an integer 200
console.log(price); //200

//js storage min max value storage
console.log(Number.MAX_VALUE); //1.7976931348623157e+308
console.log(Number.MIN_VALUE); //5e-324

//Infinity
var mayBeInfinity = Number.MAX_VALUE + Number.MAX_VALUE;
var negativeInfinity = -10 / 0;
console.log(mayBeInfinity); //infinity
console.log(negativeInfinity); //-Infinity

//NaN
console.log("a" / 2); // NaN;
console.log(NaN / 2); // NaN
console.log(NaN == NaN); // false

//Exponential Notation
//Extra large or extra small numbers can be written with scientific (exponential) notation:
let y1 = 123e5;
let z1 = 123e-5;
console.log(y1); // 12300000
console.log(z1); // 0.00123

//2.String --->'',"",` `

var fName = "selva"; //string literal
var lName = "manan";
let phrase = `can embed another ${lName}`;
console.log(fName); //selva
console.log(lName); //manan
console.log(phrase); //can embed another manan

// use \ to escape the single quote (')
let message = "I'm also a valid string";
console.log(message); //I'm also a valid string

//concat +
let str = "JavaScript";
str = str + " String";
console.log(str); //JavaScript String

//
let s = "JavaScript";
s[0] = "j";
console.log(s); //JavaScript

//
// Single quote inside double quotes:
let answer1 = "It's alright";
console.log(answer1); //It's alright

// Single quotes inside double quotes:
let answer2 = "He is called 'Johnny'";
console.log(answer2); //He is called 'Johnny'

// Double quotes inside single quotes:
let answer3 = 'He is called "Johnny"';
console.log(answer3); //He is called "Johnny"

//3.Boolean

let x11 = 5;
let y11 = 5;
let z11 = 6;
console.log(x11 == y11); // Returns true
console.log(x11 == z11); // Returns false

let inProgress = true; //Boolean Literal
let completed = false;

console.log(typeof completed); // boolean

let isGreater = 4 > 1;
console.log(isGreater);

//example boolean:
console.log(Boolean("Hi")); // true
console.log(Boolean("")); // false

console.log(Boolean(20)); // true
console.log(Boolean(Infinity)); // true
console.log(Boolean(0)); // false

console.log(Boolean({ foo: 100 })); // true on non-empty object
console.log(Boolean(null)); // false

//4.null

var h1 = null;
console.log(h1); //null
console.log(typeof h1); // object

// let myVariable = null;
// console.log(myVariable); //null
// myVariable = "harshit";
// console.log(myVariable, typeof myVariable); //harshit string
// console.log(typeof null); //object
// bug , error

//5.undefined

var weird; // Value is undefined, type is undefined
console.log(weird, typeof weird); //undefined,undefined

//.
let car = "Volvo";
car = undefined; // Value is undefined, type is undefined
console.log(car, typeof car); //undefined undefined

//6.Symbol
//ES6 2015
//unique value generate

let s1 = Symbol("hello"); //fgdfgbhdfjbghdfb12344
console.log(s1); //symbol()

console.log(Symbol() == Symbol()); // false

const first = Symbol(); //symbol
console.log(first);

const second = Symbol(); //hbjdbvsvshjchsfvg
console.log(second); //symbol

console.log(first == second); //false

//7.The bigint type
let pageView = 9007199254740991n;
console.log(typeof pageView); // 'bigint'

// BigInt:
// let myNumber = BigInt(12);
// let sameMyNumber = 123n;
// console.log(myNumber);
// console.log(Number.MAX_SAFE_INTEGER);
// console.log(myNumber+ sameMyNumber);

//
let x4 = BigInt("123456789012345678901234567890");
console.log(x4); //123456789012345678901234567890n

//Reference Data Types

//1.Arrays
var courses = ["C", "C++", "Java"]; //Array
console.log(typeof courses); //object

//.
const cars2 = ["Saab", "Volvo", "BMW"];
console.log(cars2[0]);

//2.Object
var student = {
  name: "Joes", //Object
  age: 22,
};
console.log(typeof student); //object

//.
const person3 = {
  firstName: "John",
  lastName: "Doe",
  age: 50,
  eyeColor: "blue",
};
console.log(person3.firstName);

//3.Date
var d = new Date(); //Date function
console.log(d);
console.log(typeof d); //object

//The typeof Operator

//Returns "string"
console.log(typeof "", typeof "John", typeof "John Doe"); //string string string string

//Returns "number"
console.log(typeof 0, typeof 314, typeof 3.14, typeof 3, typeof (3 + 4)); //number number number number number

/*
i.Empty Values
An empty value has nothing to do with undefined.

An empty string has both a legal value and a type.
*/
let car1 = "";
console.log(car1, typeof car1); //  string
